### ISSUE TITLE
全家福模式无法使用

### ISSUE THREAD

**Issue by idesign2018** [shadowcz007/comfyui-liveportrait#14]
![image](https://github.com/shadowcz007/comfyui-liveportrait/assets/42263070/51361a48-44d4-4314-9237-4fc654e57337)
可能是人脸太多导致的吧

![image](https://github.com/shadowcz007/comfyui-liveportrait/assets/42263070/a7a86fd9-f5ba-414a-87df-f06ee3948688)
该节点提示错误，应该链接到哪个节点？

**Comment by shadowcz007** [comment]
> ![image](https://private-user-images.githubusercontent.com/42263070/346467184-51361a48-44d4-4314-9237-4fc654e57337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODA4NDUsIm5iZiI6MTcyMDg4MDU0NSwicGF0aCI6Ii80MjI2MzA3MC8zNDY0NjcxODQtNTEzNjFhNDgtNDRkNC00MzE0LTkyMzctNGZjNjU0ZTU3MzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDE0MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNGZlMTQ3Yzk2NGFhNWIzOTM0ODdjMDhiNTk2YzQ3YzAxZTlhNjRjMDVlMzBjNzNlMDZmMTExM2VmYmJlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oF0M_4DXdvs2Jkoqk2T90qzmc_woKjbOsxXElbYeypA) 可能是人脸太多导致的吧
> 
> ![image](https://private-user-images.githubusercontent.com/42263070/346467336-a7a86fd9-f5ba-414a-87df-f06ee3948688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODA4NDUsIm5iZiI6MTcyMDg4MDU0NSwicGF0aCI6Ii80MjI2MzA3MC8zNDY0NjczMzYtYTdhODZmZDktZjViYS00MTRhLTg3ZGYtZjA2ZWUzOTQ4Njg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDE0MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMjI1Y2U1ODNlMTI0ZjBiMTEzOWJhNmQxMjdjNTYxN2MwZmE3ZDE5MDBjZTM3ZDk2ZjkxNjQzZmE0YzA0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CcV6-86VsjVoIx3vIViDzpjtPw0U_mOXafWRIsgbMOY) 该节点提示错误，应该链接到哪个节点？

修复了，是个bug
