### ISSUE TITLE
When loading the graph, the following node types were not found: LivePortraitNode

### ISSUE THREAD

**Issue by Medmehrez** [shadowcz007/comfyui-liveportrait#23]
i keep getting this even after installing all missing nodes

<img width="653" alt="image" src="https://github.com/user-attachments/assets/045a83d1-c69a-4fcb-a25c-cc96cb6e94ca">
<img width="1557" alt="image" src="https://github.com/user-attachments/assets/2175bbed-088f-45a1-a879-baf939cd0af2">

**Comment by StudioDUzes** [comment]
same problem

**Comment by thinker88** [comment]
same problem

**Comment by Medmehrez** [comment]
> same problem

I solved this by installing insightface, guide: https://github.com/Gourieff/comfyui-reactor-node

I simply followed the troubleshooting steps
