### ISSUE TITLE
UPDATE REQUIREMENTS

### ISSUE THREAD

**Issue by RGX650** [shadowcz007/comfyui-liveportrait#5]
add tyro to requirements

**Comment by GoodGoodstudy0daydayup** [comment]
i have installed the tyro package, but there is still "no module named tyro" problem

**Comment by RGX650** [comment]
@GoodGoodstudy0daydayup 
if you have the standard comfyui installation (not portable):

cd C:\...\ComfyUI\venv\Scripts
activate
pip install tyro

to verify you can also do:
pip show tyro

to verify any package conflict you can also do:
pip check
