### ISSUE TITLE
missing nodes? 

### ISSUE THREAD

**Issue by 4lt3r3go** [shadowcz007/comfyui-liveportrait#9]
![image](https://github.com/shadowcz007/comfyui-liveportrait/assets/44883288/ef8bd4dc-5384-418e-9e5c-9f9d136aef90)

![image](https://github.com/shadowcz007/comfyui-liveportrait/assets/44883288/62d96f2c-5525-46c5-ae9e-605ede4d2a4f)

install custom missing nodes wont find anything also
thank you

**Comment by niknah** [comment]
Go to comfy manager, install from git "https://github.com/shadowcz007/comfyui-mixlab-nodes"
